"""Fix API key foreign key constraints

Revision ID: 72f70a0c5ff3
Revises: ee5efb1815a7
Create Date: 2025-09-23 04:35:01.906106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f70a0c5ff3'
down_revision: Union[str, None] = 'ee5efb1815a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
