"""Add API key fields to admin users

Revision ID: 9590bd42bffb
Revises: ed9e713b4548
Create Date: 2025-09-23 04:27:28.425581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9590bd42bffb'
down_revision: Union[str, None] = 'ed9e713b4548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('api_key_hash', sa.String(length=255), nullable=True))
    op.add_column('admin_users', sa.Column('api_key_name', sa.String(length=100), nullable=True))
    op.add_column('admin_users', sa.Column('api_key_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('admin_users', sa.Column('api_key_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_admin_users_api_key_hash'), 'admin_users', ['api_key_hash'], unique=True)
    op.drop_column('reviews', 'communication')
    op.drop_column('reviews', 'academic_quality')
    op.drop_column('reviews', 'facilities')
    op.drop_column('reviews', 'safety')
    op.drop_column('reviews', 'teacher_quality')
    op.drop_column('reviews', 'extracurriculars')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('extracurriculars', sa.FLOAT(), nullable=True))
    op.add_column('reviews', sa.Column('teacher_quality', sa.FLOAT(), nullable=True))
    op.add_column('reviews', sa.Column('safety', sa.FLOAT(), nullable=True))
    op.add_column('reviews', sa.Column('facilities', sa.FLOAT(), nullable=True))
    op.add_column('reviews', sa.Column('academic_quality', sa.FLOAT(), nullable=True))
    op.add_column('reviews', sa.Column('communication', sa.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_admin_users_api_key_hash'), table_name='admin_users')
    op.drop_column('admin_users', 'api_key_expires_at')
    op.drop_column('admin_users', 'api_key_created_at')
    op.drop_column('admin_users', 'api_key_name')
    op.drop_column('admin_users', 'api_key_hash')
    # ### end Alembic commands ###
